Add support for Image-Charts as a drop-in-replacement for Google Image Charts
tgalopin/LegGoogleCharts pull request #2
Opened 2016-10-19 20:16 UTC by FGRibreau

👍

2016-10-19 20:21 UTC, tgalopin requested changes
Thanks! That's cool to see a replacement for Google Charts image.

2016-10-19 20:21 UTC, tgalopin commented on src/Leg/GCharts/BaseChart.php
> +	 * @var array
There is indentation issues in this file, here is the first.

2016-10-19 20:21 UTC, tgalopin commented on src/Leg/GCharts/BaseChart.php
> +  const IMAGECHARTS_SUPPORTED = ['bvs', 'bhs', 'bvg', 'bhg', 'bvo', 'p', 'p3', 'pc', 'pd', 'ls', 'lc', 'lxy'];
Same here.

2016-10-19 20:21 UTC, tgalopin commented on src/Leg/GCharts/BaseChart.php
> +  /**
Same here.

2016-10-19 20:23 UTC, FGRibreau commented
@tgalopin thanks for bringing that up, fixed! :)

2016-10-20 09:11 UTC, tgalopin approved these changes

2016-10-20 09:25 UTC, merged